# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from spec.models.change_data import ChangeData
from spec.models.fund_group import FundGroup
from spec.models.localized_value import LocalizedValue


class Fund(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Fund - a model defined in OpenAPI

        id: The id of this Fund [Optional].
        name: The name of this Fund.
        long_name: The long_name of this Fund [Optional].
        short_name: The short_name of this Fund [Optional].
        bank_receiver_name: The bank_receiver_name of this Fund [Optional].
        group: The group of this Fund [Optional].
        price_date: The price_date of this Fund [Optional].
        a_share_value: The a_share_value of this Fund [Optional].
        b_share_value: The b_share_value of this Fund [Optional].
        change_data: The change_data of this Fund [Optional].
        profit_projection: The profit_projection of this Fund [Optional].
        profit_projection_date: The profit_projection_date of this Fund [Optional].
        color: The color of this Fund [Optional].
        risk: The risk of this Fund [Optional].
        kiid: The kiid of this Fund [Optional].
    """
    id: Optional[str] = None
    name: LocalizedValue
    long_name: Optional[LocalizedValue] = None
    short_name: Optional[LocalizedValue] = None
    bank_receiver_name: Optional[str] = None
    group: Optional[FundGroup] = None
    price_date: Optional[date] = None
    a_share_value: Optional[float] = None
    b_share_value: Optional[float] = None
    change_data: Optional[ChangeData] = None
    profit_projection: Optional[float] = None
    profit_projection_date: Optional[date] = None
    color: Optional[str] = None
    risk: Optional[int] = None
    kiid: Optional[LocalizedValue] = None


Fund.update_forward_refs()
