# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class FundHistoryValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FundHistoryValue - a model defined in OpenAPI

        date: The date of this FundHistoryValue [Optional].
        value: The value of this FundHistoryValue [Optional].
    """
    date: Optional[date] = None
    value: Optional[str] = None

    @classmethod
    @validator("value")
    def value_pattern(cls, value):
        assert value is not None and re.match(r"^[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)$", value)
        return value


FundHistoryValue.update_forward_refs()
