# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from spec.models.change_data import ChangeData
from spec.models.fund_group import FundGroup
from spec.models.localized_value import LocalizedValue


class Fund(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Fund - a model defined in OpenAPI

        id: The id of this Fund [Optional].
        name: The name of this Fund.
        longName: The longName of this Fund [Optional].
        shortName: The shortName of this Fund [Optional].
        bankReceiverName: The bankReceiverName of this Fund [Optional].
        group: The group of this Fund [Optional].
        priceDate: The priceDate of this Fund [Optional].
        aShareValue: The aShareValue of this Fund [Optional].
        bShareValue: The bShareValue of this Fund [Optional].
        changeData: The changeData of this Fund [Optional].
        profitProjection: The profitProjection of this Fund [Optional].
        profitProjectionDate: The profitProjectionDate of this Fund [Optional].
        color: The color of this Fund [Optional].
        risk: The risk of this Fund [Optional].
        KIID: The KIID of this Fund [Optional].
    """
    id: Optional[str] = None
    name: LocalizedValue
    longName: Optional[LocalizedValue] = None
    shortName: Optional[LocalizedValue] = None
    bankReceiverName: Optional[str] = None
    group: Optional[FundGroup] = None
    priceDate: Optional[date] = None
    aShareValue: Optional[float] = None
    bShareValue: Optional[float] = None
    changeData: Optional[ChangeData] = None
    profitProjection: Optional[float] = None
    profitProjectionDate: Optional[date] = None
    color: Optional[str] = None
    risk: Optional[int] = None
    KIID: Optional[LocalizedValue] = None


Fund.update_forward_refs()
