# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class LocalizedValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LocalizedValue - a model defined in OpenAPI

        fi: The fi of this LocalizedValue.
        sv: The sv of this LocalizedValue.
        en: The en of this LocalizedValue [Optional].
    """
    fi: str
    sv: str
    en: Optional[str] = None


LocalizedValue.update_forward_refs()
