# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class MeetingTime(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MeetingTime - a model defined in OpenAPI

        startTime: The startTime of this MeetingTime.
        endTime: The endTime of this MeetingTime.
    """
    startTime: datetime
    endTime: datetime


MeetingTime.update_forward_refs()
