# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class MeetingContact(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MeetingContact - a model defined in OpenAPI

        firstName: The firstName of this MeetingContact.
        lastName: The lastName of this MeetingContact.
        email: The email of this MeetingContact [Optional].
        phone: The phone of this MeetingContact [Optional].
    """
    firstName: str
    lastName: str
    email: Optional[EmailStr] = None
    phone: Optional[str] = None


MeetingContact.update_forward_refs()
