# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from spec.models.meeting_contact import MeetingContact
from spec.models.meeting_type import MeetingType


class Meeting(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Meeting - a model defined in OpenAPI

        type: The type of this Meeting.
        time: The time of this Meeting.
        language: The language of this Meeting.
        participantCount: The participantCount of this Meeting.
        contact: The contact of this Meeting.
        additionalInformation: The additionalInformation of this Meeting [Optional].
    """
    type: MeetingType
    time: datetime
    language: str
    participantCount: int
    contact: MeetingContact
    additionalInformation: Optional[str] = None


Meeting.update_forward_refs()
