# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PortfolioHistoryValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PortfolioHistoryValue - a model defined in OpenAPI

        date: The date of this PortfolioHistoryValue [Optional].
        value: The value of this PortfolioHistoryValue [Optional].
    """
    date: Optional[date] = None
    value: Optional[int] = None


PortfolioHistoryValue.update_forward_refs()
