# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PortfolioFund(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PortfolioFund - a model defined in OpenAPI

        id: The id of this PortfolioFund.
        amount: The amount of this PortfolioFund.
        purchaseValue: The purchaseValue of this PortfolioFund.
        totalValue: The totalValue of this PortfolioFund.
    """
    id: str
    amount: float
    purchaseValue: int
    totalValue: int


PortfolioFund.update_forward_refs()
