# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from spec.models.transaction_type import TransactionType


class PortfolioTransaction(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PortfolioTransaction - a model defined in OpenAPI

        id: The id of this PortfolioTransaction [Optional].
        fundId: The fundId of this PortfolioTransaction.
        targetFundId: The targetFundId of this PortfolioTransaction [Optional].
        type: The type of this PortfolioTransaction.
        valueDate: The valueDate of this PortfolioTransaction.
        value: The value of this PortfolioTransaction.
        shareAmount: The shareAmount of this PortfolioTransaction.
        marketValue: The marketValue of this PortfolioTransaction.
        totalValue: The totalValue of this PortfolioTransaction.
        paymentDate: The paymentDate of this PortfolioTransaction.
        provision: The provision of this PortfolioTransaction.
    """
    id: Optional[str] = None
    fundId: str
    targetFundId: Optional[str] = None
    type: TransactionType
    valueDate: date
    value: int
    shareAmount: float
    marketValue: int
    totalValue: int
    paymentDate: date
    provision: int


PortfolioTransaction.update_forward_refs()
