# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from spec.models.localized_value import LocalizedValue


class Security(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Security - a model defined in OpenAPI

        id: The id of this Security [Optional].
        fundId: The fundId of this Security.
        name: The name of this Security.
        currency: The currency of this Security.
    """
    id: Optional[str] = None
    fundId: str
    name: LocalizedValue
    currency: str


Security.update_forward_refs()
