# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2021-10-25T07:23:21+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional
from uuid import UUID

from fastapi import FastAPI, Path, Query

from .models import Fund, HistoricalValue

app = FastAPI(
    version='1.0.0',
    title='Taskusalkku API-spec',
)


@app.get('/v1/funds', response_model=List[Fund])
def list_funds(
    first_result: Optional[int] = Query(None, alias='firstResult'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
) -> List[Fund]:
    """
    List funds.
    """
    pass


@app.get('/v1/funds/{fund_id}', response_model=Fund)
def find_fund(fund_id: UUID = Path(..., alias='fundId')) -> Fund:
    """
    Find a fund.
    """
    pass


@app.get('/v1/funds/{fund_id}/historicalValues', response_model=List[HistoricalValue])
def list_historical_values(
    fund_id: UUID = Path(..., alias='fundId'),
    first_result: Optional[int] = Query(None, alias='firstResult'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    start_date: Optional[date] = Query(None, alias='startDate'),
    end_date: Optional[date] = Query(None, alias='endDate'),
) -> List[HistoricalValue]:
    """
    Lists historical values
    """
    pass


@app.get('/v1/system/ping', response_model=None)
def ping() -> None:
    """
    Replies with pong
    """
    pass
