# generated by fastapi-codegen:
#   filename:  taskusalkku-spec/swagger.yaml
#   timestamp: 2021-10-25T07:23:21+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Error(BaseModel):
    code: int
    message: str


class LocalizedValue(BaseModel):
    fi: str
    sv: str


class FundGroup(Enum):
    PASSIVE = 'PASSIVE'
    ACTIVE = 'ACTIVE'
    BALANCED = 'BALANCED'
    FIXED_INCOME = 'FIXED_INCOME'
    DIMENSION = 'DIMENSION'
    SPILTAN = 'SPILTAN'


class ChangeData(BaseModel):
    field_1dChange: Optional[float] = Field(
        None, alias='1dChange', description='1 day change'
    )
    field_1mChange: Optional[float] = Field(
        None, alias='1mChange', description='1 month change'
    )
    field_1yChange: Optional[float] = Field(
        None, alias='1yChange', description='1 year change'
    )
    field_3yChange: Optional[float] = Field(
        None, alias='3yChange', description='3 years change'
    )
    field_5yChange: Optional[float] = Field(
        None, alias='5yChange', description='5 years change'
    )
    field_10yChange: Optional[float] = Field(
        None, alias='10yChange', description='10 years change'
    )
    field_15yChange: Optional[float] = Field(
        None, alias='15yChange', description='15 years change'
    )
    field_20yChange: Optional[float] = Field(
        None, alias='20yChange', description='20 years change'
    )


class HistoricalValue(BaseModel):
    date: Optional[date] = Field(None, description='Date of historical value')
    value: Optional[float] = Field(None, description='Historical value')


class Fund(BaseModel):
    id: Optional[UUID] = Field(None, description='Fund object id in UUID format')
    name: LocalizedValue
    longName: Optional[LocalizedValue] = None
    shortName: Optional[LocalizedValue] = None
    bankReceiverName: Optional[str] = Field(None, description='Bank receiver name')
    group: Optional[FundGroup] = None
    priceDate: Optional[date] = Field(None, description='Price date')
    aShareValue: Optional[float] = Field(None, description='Share value A')
    bShareValue: Optional[float] = Field(None, description='Share value B')
    changeData: Optional[ChangeData] = None
    profitProjection: Optional[float] = Field(None, description='Profit projection')
    profitProjectionDate: Optional[date] = Field(
        None, description='Profit projection date'
    )
    color: Optional[str] = Field(None, description='Fund color')
    risk: Optional[int] = Field(None, description='Fund risk level')
    KIID: Optional[LocalizedValue] = None
