"""create portfolio table

Revision ID: 0006
Revises: 0005
Create Date: 2021-12-06 14:25:18.323014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import BINARY

# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
                    sa.Column('id', BINARY(16), nullable=False),
                    sa.Column('portfolio_id', sa.String(length=20), nullable=True),
                    sa.Column('company_code', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('portfolio_id')
                    )
    op.create_index(op.f('ix_portfolio_company_code'), 'portfolio', ['company_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_company_code'), table_name='portfolio')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
