"""create security table

Revision ID: 0004
Revises: 0003
Create Date: 2021-12-06 14:25:18.323014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import BINARY

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security',
                    sa.Column('id', BINARY(16), nullable=False),
                    sa.Column('security_id', sa.String(length=20), nullable=False),
                    sa.Column('currency', sa.CHAR(length=3), nullable=True),
                    sa.Column('pe_corr', sa.DECIMAL(precision=8, scale=4), nullable=True),
                    sa.Column('isin', sa.String(length=12), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'security_id')
                    )
    op.create_index(op.f('ix_security_security_id'), 'security', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_security_id'), table_name='security')
    op.drop_table('security')
    # ### end Alembic commands ###
