"""create log table

Revision ID: 0007
Revises: 0006
Create Date: 2021-12-06 14:25:18.323014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import BINARY

# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_log',
                    sa.Column('transaction_number', sa.Integer(), nullable=False),
                    sa.Column('transaction_code', sa.CHAR(length=2), nullable=True),
                    sa.Column('transaction_date', sa.DateTime(), nullable=True),
                    sa.Column('company_code', sa.String(length=20), nullable=True),
                    sa.Column('portfolio_id', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('transaction_number')
                    )
    op.create_index(op.f('ix_portfolio_log_company_code'), 'portfolio_log', ['company_code'], unique=False)
    op.create_index(op.f('ix_portfolio_log_portfolio_id'), 'portfolio_log', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_log_transaction_code'), 'portfolio_log', ['transaction_code'], unique=False)
    op.create_index(op.f('ix_portfolio_log_transaction_date'), 'portfolio_log', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_portfolio_log_transaction_number'), 'portfolio_log', ['transaction_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_log_transaction_number'), table_name='portfolio_log')
    op.drop_index(op.f('ix_portfolio_log_transaction_date'), table_name='portfolio_log')
    op.drop_index(op.f('ix_portfolio_log_transaction_code'), table_name='portfolio_log')
    op.drop_index(op.f('ix_portfolio_log_portfolio_id'), table_name='portfolio_log')
    op.drop_index(op.f('ix_portfolio_log_company_code'), table_name='portfolio_log')
    op.drop_table('portfolio_log')
    # ### end Alembic commands ###
